### ISSUE TITLE
Upload Word2Vec pretrained models

### ISSUE THREAD

**Issue by akoksal** [akoksal/Turkish-Word2Vec#3]
Upload pretrained models with and without lemmatization to google drive.

Deadline: 28.02.2018

**Comment by github53** [comment]
Hello Sir, I couldn't download the pretrained model. Could you check the download link. Thank you

**Comment by akoksal** [comment]
Hello, I added link for pretrained model in readme and wiki page. You can check these pages for more details. Thank you for your support.

**Comment by github53** [comment]
thank you very much
