### ISSUE TITLE
Reading corpus

### ISSUE THREAD

**Issue by alihannka** [akoksal/Turkish-Word2Vec#6]
firstly thanks for sharing this source.

my problem is that you used wikicorpus for opening your corpus but i built mine text without wiki. how could i implement mine ? 

wiki = WikiCorpus(inputFile, lemmatize=False,tokenizer_func = tokenize_tr)

**Comment by akoksal** [comment]
As I described in the [Training Word2vec Model](https://github.com/akoksal/Turkish-Word2Vec/wiki/4.-Training-Word2Vec-Model), if you create a txt file that contains each document in your corpus as a line without punctuations, you can use `trainCorpus.py` to train a word2vec model.

You can check out `wiki.tr.txt` file to completely understand the format of the intermediate file but it is simple as I explained.
